DROP USER IF EXISTS app;

DROP VIEW IF EXISTS trolls;
DROP VIEW IF EXISTS projects;


DROP TRIGGER IF EXISTS on_new_user_trig ON users;
DROP TRIGGER IF EXISTS on_vote_trig ON votes;
DROP TRIGGER IF EXISTS on_new_action ON actions;

DROP FUNCTION IF EXISTS on_new_action();
DROP FUNCTION IF EXISTS update_votes();
DROP FUNCTION IF EXISTS new_user();


DROP INDEX IF EXISTS users.trolls_index;
DROP TABLE IF EXISTS votes CASCADE;
DROP TABLE IF EXISTS actions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS ID CASCADE;
DROP TYPE IF EXISTS id_type_enum;
